# SQL
spring:
  application:
    name: xtream
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=xtream;encrypt=false
    password: 123456
    username: sa
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
# REDIS
  data:
    redis:
      host: localhost
      port: 6379
# LOG
logging:
  level:
    root: debug
    org.springframework.cache: debug
    org.springframework.security: debug
# SWAGGER
springdoc:
  swagger-ui:
    path: /swagger-ui.html



